#!/usr/bin/env bash

# Shell script to convert files from graphviz DOT format to svg

set -e

if ! command -v dot >/dev/null; then
    printf "Graphviz not installed\n" >&2
    exit 127
fi

output_set=false

POSITIONAL_ARGS=()

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    -o|--output)
        output_set=true
        output="$2"
        shift
        ;;
    -i|--input)
        input="$2"
        shift
        ;;
    *)
        printf "Unknown argument: %s\n" "$1" >&2
        exit 1
        ;;
    esac
    shift
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters


if [ "$output_set" = true ]; then
    # clean up the DOT and save it
    nop $input > "generated/${output}.gv"

    # Use the clean DOT to generate and save an svg
    dot -Tsvg -o "generated/${output}.svg" < "generated/${output}.gv"
else
    # save nothing and spit out the svg
    nop $input | dot -Tsvg < /dev/stdin
fi

